[package]
name = "rfw"
version = "0.1.9"
edition.workspace = true

license.workspace = true

[dependencies]
rfw-common = { path = "../rfw-common", features = ["user"] }

anyhow = { workspace = true, default-features = true }
aya = { workspace = true }
aya-log = { workspace = true }
env_logger = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
tokio = { workspace = true, features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "net",
    "signal",
] }
clap = { workspace = true, features = ["derive"] }
reqwest = { version = "0.13.2", default-features = false, features = ["json", "rustls"] }
serde = { version = "1.0", features = ["derive"] }
axum = { version = "0.8.8", features = ["macros"] }
tower-http = { version = "0.6", features = ["cors"] }
[build-dependencies]
anyhow = { workspace = true }
aya-build = { workspace = true }
cargo_metadata = { workspace = true }

[[bin]]
name = "rfw"
path = "src/main.rs"
